[workspace]
members = ["config"]

[package]
name = "drone"
version = "0.9.0"
authors = ["Valentine Valyaeff <valentine.valyaeff@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/drone-os/drone"
readme = "README.md"
edition = "2018"
default-run = "drone"
description = """
CLI utility for Drone, an Embedded Operating System.
"""

[badges]
maintenance = { status = "actively-developed" }

[dependencies.drone-config]
version = "=0.9.0"
path = "config"

[dependencies]
exitfailure = "0.5"
failure = { version = "0.1", features = ["derive"] }
handlebars = "2"
structopt = "0.2"
walkdir = "2"
