[workspace]
members = ["config"]

[package]
name = "drone"
version = "0.9.0"
authors = ["Valentine Valyaeff <valentine.valyaeff@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/drone-os/drone"
readme = "README.md"
edition = "2018"
default-run = "drone"
description = """
CLI utility for Drone, an Embedded Operating System.
"""

[badges]
maintenance = { status = "actively-developed" }

[dependencies.drone-config]
version = "=0.9.0"
path = "config"

[dependencies]
env_logger = "0.6"
exitfailure = "0.5"
failure = { version = "0.1", features = ["derive"] }
handlebars = "2"
libc = "0.2"
log = "0.4"
serde_json = "1"
structopt = "0.3"
tempfile = "3"
termcolor = "1"
walkdir = "2"
