[package]
name = "drone-config"
version = "0.9.0"
authors = ["Valentine Valyaeff <valentine.valyaeff@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/drone-os/drone"
edition = "2018"
description = """
Configuration file support for Drone, an Embedded Operating System.
"""

[dependencies]
serde = { version = "1", features = ["derive"] }
toml = "0.4"
failure = { version = "0.1" }
