[package]
name = "drone-config"
version = "0.10.0"
authors = ["Valentine Valyaeff <valentine.valyaeff@gmail.com>"]
edition = "2018"
repository = "https://github.com/drone-os/drone"
homepage = "https://www.drone-os.com/"
license = "MIT OR Apache-2.0"
description = """
Configuration for Drone, an Embedded Operating System.
"""

[dependencies]
failure = { version = "0.1" }
serde = { version = "1", features = ["derive"] }
toml = "0.4"
